engines:
  brakeman:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      no-unused-expressions:
        enabled: false
      TODO:
        enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- dist/**/*
