language: node_js

node_js:
  - 6
  - 6.6
  - 6.5
  - 6.4
  - 6.3
  - 6.2
  - 6.1
  - 6.0
  - 5
  - 5.11
  - 5.10
  - 5.9
  - 5.8
  - 5.7
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - 5.1
  - 5.0
  - 4
  - 4.5
  - 4.4
  - 4.3

addons:
  sauce_connect:
    username: "chge"
  jwt:
    secure: "uh1UCBdoFZituOcZPEkzHFdarr98cGxY761p11l9cDFlaMKhHAitSdo8PxhgORMNRUrGuThtj0/4NCS/HtXvToIyzj4z0Z+Y6PPik3NelR+IdL4dSgDCRmZGxsWORJmfF4NlJD8jLYhqHM4tpc5ytjHge2RbbS+ay6sobb92gLM8P5XLtJ+wuad/DnGfCedAIwud0dIlPnHBygORQZ8uvuz7f/dThu7waXsmeIBry+otnweNuQ6O3UYN2hw44BHZZ6LBxKTkYvDXzZ1toZ7UyGyM6dsHpg35+yf9j9JFg7c2b6e9SB72jYtMA+a2XZpF1c029Kbmp9OqwNerfaOxRKSjAUpfUCDWO8E5QwW+x5epqa48CRCxjEXv013Vv0n6tY1MTagGtXjduUHFU6/qOXEEQWnctlDlF0/nml346PFDm0x52C/0BmMEg0XW6wBpwiYe68VIMVPHUIgV2vqrA8qbQmfR+TbHJNNEOKcGgUkn23qrAK1BAfuDqKxjKwoQRtw7M+96qRiGBYAY4JMdlzyXGSPLDdB+w6YaQkf/ZL03xom66nNOuol4RWVBHT2dBcfuVU7v0V+t/iw/FnNsyEFBuJ9w/cYst47JT2aRgmlfjyrzoGsdUuZvERVdrLV0HJV1195kKFMXaqky+osh0T8b5yYNpEjbm7zediIG34k="

notifications:
  email: false
