dist: trusty
sudo: false

language: node_js

matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      addons: &firefox
        firefox: "59.0"
      script: &test
        - phantomjs --version
        - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3
        - npm test
    - { node_js: "node", addons: *firefox, script: *test }
    - { node_js: "10.5", addons: *firefox, script: *test }
    - { node_js: "10.0", addons: *firefox, script: *test }
    - { node_js: "9.8", addons: *firefox, script: *test }
    - { node_js: "9.0", addons: *firefox, script: *test }
    - { node_js: "8.11", addons: *firefox, script: *test }
    - { node_js: "8.0", addons: *firefox, script: *test }
    - node_js: "lts/*"
      addons: &sauce
        hosts:
          - tasty.local
        jwt:
          secure: xKrWkJu58y5lmkZzpPr5bGt0TAkFo2053Pw4BPU9x8vAFINGeUAvj8VEIyQn5MMstntG1xO96ih/WAq0OhHCxwZgWLpUNxmzC1kJC93eyMHIlxttPL90lQIBOTtGzGLTkQe3HuGRwDmXZPehURkElPwWPUvPVyQHgyxLX78T2/ktBkElm/wp7MTSe2j0Adzo4Wt3Aga3WzTRde9gW5IH+/U/JXtpj247/AQCvMH2wmQSRP2XqrqAPF1y6jA3CECiTLpX0zVPnup62/S3QL5WTQspB37E7qNutruewlItxqy+vWJ40zredXIiZKDoXq6IA6h8SYktzXNPGMo/5fBP1gEEBKkgPG0A6vT/CaUvSyShx3zwMMT8WnPNyOVpNDxXw2JAP3ru9kj717cJxswIWvzLfc+MEX5kdOwHtB/zTz3xBYbgpjJ/SbJ3l0XdVQ5owxU1OCBVgwarYFXRFpORctGtE9BIgns5r8ukmQCvZGGG3UUCQxiOKwdIYZh1YZ4JJpvdQMHs0RESoRSWQoQiwWwfkbseCC7uSROtojgQp05x6qUHPA4VdoN9MGx+PDLItlhb/VB7T6YuVPPnkB2a6rfrw3XC7eZidCgXK9mKG2k4cnfPQ9KfaS5zefo39ghgFAsKc1xbPk/ldGfKVoNkNTSTLA0gYnLn5o2ALJJS8u4=
        sauce_connect:
          username: tasty
          direct_domains: all
          no_ssl_bump_domains: all
          tunnel_domains: tasty.local
      script: &support
        - export DEBUG=tasty* DEBUG_COLORS=true
        - npm run support
    - { node_js: "node", addons: *sauce, script: *support }
    - { node_js: "10.5.0", addons: *sauce, script: *support }
    - { node_js: "10.4.1", addons: *sauce, script: *support }
    - { node_js: "10.4.0", addons: *sauce, script: *support }
    - { node_js: "10.3.0", addons: *sauce, script: *support }
    - { node_js: "10.2.1", addons: *sauce, script: *support }
    - { node_js: "10.2.0", addons: *sauce, script: *support }
    - { node_js: "10.1.0", addons: *sauce, script: *support }
    - { node_js: "10.0.0", addons: *sauce, script: *support }
    - { node_js: "9.11.2", addons: *sauce, script: *support }
    - { node_js: "9.11.1", addons: *sauce, script: *support }
    - { node_js: "9.11.0", addons: *sauce, script: *support }
    - { node_js: "9.10.1", addons: *sauce, script: *support }
    - { node_js: "9.10.0", addons: *sauce, script: *support }
    - { node_js: "9.9.0", addons: *sauce, script: *support }
    - { node_js: "9.8.0", addons: *sauce, script: *support }
    - { node_js: "9.7.1", addons: *sauce, script: *support }
    - { node_js: "9.7.0", addons: *sauce, script: *support }
    - { node_js: "9.6.1", addons: *sauce, script: *support }
    - { node_js: "9.6.0", addons: *sauce, script: *support }
    - { node_js: "9.5.0", addons: *sauce, script: *support }
    - { node_js: "9.4.0", addons: *sauce, script: *support }
    - { node_js: "9.3.0", addons: *sauce, script: *support }
    - { node_js: "9.2.1", addons: *sauce, script: *support }
    - { node_js: "9.2.0", addons: *sauce, script: *support }
    - { node_js: "9.1.0", addons: *sauce, script: *support }
    - { node_js: "9.0.0", addons: *sauce, script: *support }
    - { node_js: "8.11.3", addons: *sauce, script: *support }
    - { node_js: "8.11.2", addons: *sauce, script: *support }
    - { node_js: "8.11.1", addons: *sauce, script: *support }
    - { node_js: "8.11.0", addons: *sauce, script: *support }
    - { node_js: "8.10.0", addons: *sauce, script: *support }
    - { node_js: "8.9.4", addons: *sauce, script: *support }
    - { node_js: "8.9.3", addons: *sauce, script: *support }
    - { node_js: "8.9.2", addons: *sauce, script: *support }
    - { node_js: "8.9.1", addons: *sauce, script: *support }
    - { node_js: "8.9.0", addons: *sauce, script: *support }
    - { node_js: "8.8.1", addons: *sauce, script: *support }
    - { node_js: "8.8.0", addons: *sauce, script: *support }
    - { node_js: "8.7.0", addons: *sauce, script: *support }
    - { node_js: "8.6.0", addons: *sauce, script: *support }
    - { node_js: "8.5.0", addons: *sauce, script: *support }
    - { node_js: "8.4.0", addons: *sauce, script: *support }
    - { node_js: "8.3.0", addons: *sauce, script: *support }
    - { node_js: "8.2.1", addons: *sauce, script: *support }
    - { node_js: "8.2.0", addons: *sauce, script: *support }
    - { node_js: "8.1.4", addons: *sauce, script: *support }
    - { node_js: "8.1.3", addons: *sauce, script: *support }
    - { node_js: "8.1.2", addons: *sauce, script: *support }
    - { node_js: "8.1.1", addons: *sauce, script: *support }
    - { node_js: "8.1.0", addons: *sauce, script: *support }
    - { node_js: "8.0.0", addons: *sauce, script: *support }
  allow_failures:
    - script: *support

notifications:
  email: false
