environment:
  matrix:
    - nodejs_version: "7.9"
    - nodejs_version: "7.8"
    - nodejs_version: "7.1"
    - nodejs_version: "7.0"
    - nodejs_version: "6.10"
    - nodejs_version: "6.9"
    - nodejs_version: "6.1"
    - nodejs_version: "6.0"
    - nodejs_version: "5.12"
    - nodejs_version: "5.11"
    - nodejs_version: "5.1"
    - nodejs_version: "5.0"
    - nodejs_version: "4.8"
    - nodejs_version: "4.7"
    - nodejs_version: "4.4"
    - nodejs_version: "4.3"

platform:
  - x86
  - x64

install:
  - ps: Update-AppveyorBuild -Version (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run appveyor

build: off
